services:
  postgres:
    container_name: postgres-bsn
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-bsn-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d book_social_network"]
      interval: 5s
      timeout: 5s
      retries: 5

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-bsn-net

  spring-app:
    container_name: spring-bsn
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
      mail-dev:
        condition: service_started
    networks:
      - spring-bsn-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped

networks:
  spring-bsn-net:
    driver: bridge

volumes:
  postgres:
    driver: local